<?php
return array (
  'mp4' => 
  array (
    'status' => '1',
    'from' => 'mp4',
    'show' => '高清MP4',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1080,
    'tip' => '无需安装任何插件',
    'id' => 'mp4',
  ),
  'm3u8' => 
  array (
    'status' => '1',
    'from' => 'm3u8',
    'show' => '高清m3u8',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1079,
    'tip' => '无需安装任何插件',
    'id' => 'm3u8',
  ),
  'ckplayer' => 
  array (
    'status' => '1',
    'from' => 'ckplayer',
    'show' => 'ck直播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1078,
    'tip' => '无需安装任何插件',
    'id' => 'ckplayer',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => '豆瓣在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1077',
    'tip' => '无需安装任何插件',
    'id' => 'dbm3u8',
  ),
  'dbyun' => 
  array (
    'status' => '1',
    'from' => 'dbyun',
    'show' => '豆瓣云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1076,
    'tip' => '无需安装任何插件',
    'id' => 'dbyun',
  ),
  'gqm3u8' => 
  array (
    'status' => '1',
    'from' => 'gqm3u8',
    'show' => '高清在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1075',
    'tip' => '无需安装任何插件',
    'id' => 'gqm3u8',
  ),
  'gqyun' => 
  array (
    'status' => '1',
    'from' => 'gqyun',
    'show' => '高清云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1074,
    'tip' => '无需安装任何插件',
    'id' => 'gqyun',
  ),
  'zkm3u8' => 
  array (
    'status' => '1',
    'from' => 'zkm3u8',
    'show' => '最快在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1073,
    'tip' => '无需安装任何插件',
    'id' => 'zkm3u8',
  ),
  'zkyun' => 
  array (
    'status' => '1',
    'from' => 'zkyun',
    'show' => '最快云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1072,
    'tip' => '无需安装任何插件',
    'id' => 'zkyun',
  ),
  '172m3u8' => 
  array (
    'status' => '1',
    'from' => '172m3u8',
    'show' => '172在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1071,
    'tip' => '无需安装任何插件',
    'id' => '172m3u8',
  ),
  '172zy' => 
  array (
    'status' => '1',
    'from' => '172zy',
    'show' => '172云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1070,
    'tip' => '无需安装任何插件',
    'id' => '172zy',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '八戒在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1069,
    'tip' => '无需安装任何插件',
    'id' => 'bjm3u8',
  ),
  'bjyun' => 
  array (
    'status' => '1',
    'from' => 'bjyun',
    'show' => '八戒云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1068,
    'tip' => '无需安装任何插件',
    'id' => 'bjyun',
  ),
  'wlm3u8' => 
  array (
    'status' => '1',
    'from' => 'wlm3u8',
    'show' => '卧龙在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1068',
    'tip' => '无需安装任何插件',
    'id' => 'wlm3u8',
  ),
  'jdym3u8' => 
  array (
    'status' => '1',
    'from' => 'jdym3u8',
    'show' => '筋斗在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1066',
    'tip' => '无需安装任何插件',
    'id' => 'jdym3u8',
  ),
  'jdyzy' => 
  array (
    'status' => '1',
    'from' => 'jdyzy',
    'show' => '筋斗云',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1064,
    'tip' => '无需安装任何插件',
    'id' => 'jdyzy',
  ),
  'subom3u8' => 
  array (
    'status' => '1',
    'from' => 'subom3u8',
    'show' => '速播在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1063,
    'tip' => '无需安装任何插件',
    'id' => 'subom3u8',
  ),
  'suboyun' => 
  array (
    'status' => '1',
    'from' => 'suboyun',
    'show' => '速播云',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1062,
    'tip' => '无需安装任何插件',
    'id' => 'suboyun',
  ),
  'muaoyun' => 
  array (
    'status' => '1',
    'from' => 'muaoyun',
    'show' => '秒播云',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1061,
    'tip' => '无需安装任何插件',
    'id' => 'muaoyun',
  ),
  'miaom3u8' => 
  array (
    'status' => '1',
    'from' => 'miaom3u8',
    'show' => '秒播在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1060,
    'tip' => '无需安装任何插件',
    'id' => 'miaom3u8',
  ),
  '5am3u8' => 
  array (
    'status' => '1',
    'from' => '5am3u8',
    'show' => '5A在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1059,
    'tip' => '无需安装任何插件',
    'id' => '5am3u8',
  ),
  '5ayun' => 
  array (
    'status' => '1',
    'from' => '5ayun',
    'show' => '5A云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1058,
    'tip' => '无需安装任何插件',
    'id' => '5ayun',
  ),
  '129m3u8' => 
  array (
    'status' => '1',
    'from' => '129m3u8',
    'show' => '129在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1057,
    'tip' => '无需安装任何插件',
    'id' => '129m3u8',
  ),
  '129zy' => 
  array (
    'status' => '1',
    'from' => '129zy',
    'show' => '129云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1056,
    'tip' => '无需安装任何插件',
    'id' => '129zy',
  ),
  '131m3u8' => 
  array (
    'status' => '1',
    'from' => '131m3u8',
    'show' => '131在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1055,
    'tip' => '无需安装任何插件',
    'id' => '131m3u8',
  ),
  '131zy' => 
  array (
    'status' => '1',
    'from' => '131zy',
    'show' => '131云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1054,
    'tip' => '无需安装任何插件',
    'id' => '131zy',
  ),
  '135m3u8' => 
  array (
    'status' => '1',
    'from' => '135m3u8',
    'show' => '135在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1053',
    'tip' => '无需安装任何插件',
    'id' => '135m3u8',
  ),
  '135zy' => 
  array (
    'status' => '1',
    'from' => '135zy',
    'show' => '135云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1052,
    'tip' => '无需安装任何插件',
    'id' => '135zy',
  ),
  '156m3u8' => 
  array (
    'status' => '1',
    'from' => '156m3u8',
    'show' => '156在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1051,
    'tip' => '无需安装任何插件',
    'id' => '156m3u8',
  ),
  '156yun' => 
  array (
    'status' => '1',
    'from' => '156yun',
    'show' => '156云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1050,
    'tip' => '无需安装任何插件',
    'id' => '156yun',
  ),
  '1977zy' => 
  array (
    'status' => '1',
    'from' => '1977zy',
    'show' => '1977云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1049,
    'tip' => '无需安装任何插件',
    'id' => '1977zy',
  ),
  '33uu' => 
  array (
    'status' => '1',
    'from' => '33uu',
    'show' => '33云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1048,
    'tip' => '无需安装任何插件',
    'id' => '33uu',
  ),
  '33uuck' => 
  array (
    'status' => '1',
    'from' => '33uuck',
    'show' => '33在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1047,
    'tip' => '无需安装任何插件',
    'id' => '33uuck',
  ),
  '35m3u8' => 
  array (
    'status' => '1',
    'from' => '35m3u8',
    'show' => '35在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1046',
    'tip' => '无需安装任何插件',
    'id' => '35m3u8',
  ),
  '35yun' => 
  array (
    'status' => '1',
    'from' => '35yun',
    'show' => '35云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1045',
    'tip' => '无需安装任何插件',
    'id' => '35yun',
  ),
  '91yun' => 
  array (
    'status' => '1',
    'from' => '91yun',
    'show' => '91云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1042,
    'tip' => '无需安装任何插件',
    'id' => '91yun',
  ),
  '97m3u8' => 
  array (
    'status' => '1',
    'from' => '97m3u8',
    'show' => '97在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1041,
    'tip' => '无需安装任何插件',
    'id' => '97m3u8',
  ),
  '97zy' => 
  array (
    'status' => '1',
    'from' => '97zy',
    'show' => '97云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1040,
    'tip' => '无需安装任何插件',
    'id' => '97zy',
  ),
  '97zyck' => 
  array (
    'status' => '1',
    'from' => '97zyck',
    'show' => '97CK在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1039,
    'tip' => '无需安装任何插件',
    'id' => '97zyck',
  ),
  '9zav' => 
  array (
    'status' => '1',
    'from' => '9zav',
    'show' => '久爱云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1038,
    'tip' => '无需安装任何插件',
    'id' => '9zav',
  ),
  'bwm3u8' => 
  array (
    'status' => '1',
    'from' => 'bwm3u8',
    'show' => '百万在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1037,
    'tip' => '无需安装任何插件',
    'id' => 'bwm3u8',
  ),
  'bwyun' => 
  array (
    'status' => '1',
    'from' => 'bwyun',
    'show' => '百万云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1036,
    'tip' => '无需安装任何插件',
    'id' => 'bwyun',
  ),
  'ckm3u8' => 
  array (
    'status' => '1',
    'from' => 'ckm3u8',
    'show' => '酷云在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1035',
    'tip' => '无需安装任何插件',
    'id' => 'ckm3u8',
  ),
  'ckyun' => 
  array (
    'status' => '1',
    'from' => 'ckyun',
    'show' => 'CK云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1034,
    'tip' => '无需安装任何插件',
    'id' => 'ckyun',
  ),
  'dadi' => 
  array (
    'status' => '1',
    'from' => 'dadi',
    'show' => '大地云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1033,
    'tip' => '无需安装任何插件',
    'id' => 'dadi',
  ),
  'dadim3u8' => 
  array (
    'status' => '1',
    'from' => 'dadim3u8',
    'show' => '大地在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1032,
    'tip' => '无需安装任何插件',
    'id' => 'dadim3u8',
  ),
  'gom3u8' => 
  array (
    'status' => '1',
    'from' => 'gom3u8',
    'show' => '共在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1031,
    'tip' => '无需安装任何插件',
    'id' => 'gom3u8',
  ),
  'hkm3u8' => 
  array (
    'status' => '1',
    'from' => 'hkm3u8',
    'show' => '哈酷在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1030,
    'tip' => '无需安装任何插件',
    'id' => 'hkm3u8',
  ),
  'hkzy' => 
  array (
    'status' => '1',
    'from' => 'hkzy',
    'show' => '哈酷云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1029,
    'tip' => '无需安装任何插件',
    'id' => 'hkzy',
  ),
  'ixx' => 
  array (
    'status' => '1',
    'from' => 'ixx',
    'show' => '爱叉云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1028,
    'tip' => '无需安装任何插件',
    'id' => 'ixx',
  ),
  'jpm3u8' => 
  array (
    'status' => '1',
    'from' => 'jpm3u8',
    'show' => '精品在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1027,
    'tip' => '无需安装任何插件',
    'id' => 'jpm3u8',
  ),
  'jpyun' => 
  array (
    'status' => '1',
    'from' => 'jpyun',
    'show' => '精品云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1026,
    'tip' => '无需安装任何插件',
    'id' => 'jpyun',
  ),
  'jsm3u8' => 
  array (
    'status' => '1',
    'from' => 'jsm3u8',
    'show' => '极速在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1025,
    'tip' => '无需安装任何插件',
    'id' => 'jsm3u8',
  ),
  'jsyun' => 
  array (
    'status' => '1',
    'from' => 'jsyun',
    'show' => '极速云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1024,
    'tip' => '无需安装任何插件',
    'id' => 'jsyun',
  ),
  'kakam3u8' => 
  array (
    'status' => '1',
    'from' => 'kakam3u8',
    'show' => '卡卡在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1023,
    'tip' => '无需安装任何插件',
    'id' => 'kakam3u8',
  ),
  'kakayun' => 
  array (
    'status' => '1',
    'from' => 'kakayun',
    'show' => '卡卡云',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1022,
    'tip' => '无需安装任何插件',
    'id' => 'kakayun',
  ),
  'kankan' => 
  array (
    'status' => '1',
    'from' => 'kankan',
    'show' => '看看云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1021,
    'tip' => '无需安装任何插件',
    'id' => 'kankan',
  ),
  'kuyun' => 
  array (
    'status' => '1',
    'from' => 'kuyun',
    'show' => '酷云',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1018,
    'tip' => '无需安装任何插件',
    'id' => 'kuyun',
  ),
  'link' => 
  array (
    'status' => '1',
    'from' => 'link',
    'show' => '外链视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1017',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'mbm3u8' => 
  array (
    'status' => '1',
    'from' => 'mbm3u8',
    'show' => 'MP4吧在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1016,
    'tip' => '无需安装任何插件',
    'id' => 'mbm3u8',
  ),
  'mbyun' => 
  array (
    'status' => '1',
    'from' => 'mbyun',
    'show' => 'MP4吧云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1015,
    'tip' => '无需安装任何插件',
    'id' => 'mbyun',
  ),
  'xhgzy' => 
  array (
    'status' => '1',
    'from' => 'xhgzy',
    'show' => '小黄瓜在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1014,
    'tip' => '无需安装任何插件',
    'id' => 'xhgzy',
  ),
  'xinm3u8' => 
  array (
    'status' => '1',
    'from' => 'xinm3u8',
    'show' => '最新在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1013,
    'tip' => '无需安装任何插件',
    'id' => 'xinm3u8',
  ),
  'xinyun' => 
  array (
    'status' => '1',
    'from' => 'xinyun',
    'show' => '最新云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1012,
    'tip' => '无需安装任何插件',
    'id' => 'xinyun',
  ),
  'yjm3u8' => 
  array (
    'status' => '1',
    'from' => 'yjm3u8',
    'show' => '永久在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1011,
    'tip' => '无需安装任何插件',
    'id' => 'yjm3u8',
  ),
  'yjyun' => 
  array (
    'status' => '1',
    'from' => 'yjyun',
    'show' => '永久云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1010,
    'tip' => '无需安装任何插件',
    'id' => 'yjyun',
  ),
  'yzm' => 
  array (
    'status' => '1',
    'from' => 'yzm',
    'show' => 'C云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1009,
    'tip' => '无需安装任何插件',
    'id' => 'yzm',
  ),
  'm1905' => 
  array (
    'status' => '1',
    'from' => 'm1905',
    'show' => 'M1905视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1008',
    'tip' => '无需安装任何插件',
    'id' => 'm1905',
  ),
  'zuidall' => 
  array (
    'status' => '1',
    'from' => 'zuidall',
    'show' => '最大云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1008,
    'tip' => '无需安装任何插件',
    'id' => 'zuidall',
  ),
  'zuidam3u8' => 
  array (
    'status' => '1',
    'from' => 'zuidam3u8',
    'show' => '最大在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => 1007,
    'tip' => '无需安装任何插件',
    'id' => 'zuidam3u8',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  '605yun' => 
  array (
    'status' => '1',
    'from' => '605yun',
    'show' => '605云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '104',
    'tip' => '无需安装任何插件',
    'id' => '605yun',
  ),
  '605m3u8' => 
  array (
    'status' => '1',
    'from' => '605m3u8',
    'show' => '605在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '102',
    'tip' => '无需安装任何插件',
    'id' => '605m3u8',
  ),
  'kkyun' => 
  array (
    'status' => '1',
    'from' => 'kkyun',
    'show' => '酷酷云播',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '101',
    'tip' => '无需安装任何插件',
    'id' => 'kkyun',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => '酷酷在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '100',
    'tip' => '无需安装任何插件',
    'id' => 'kkm3u8',
  ),
);